CONTRIBUTING.md

This PR adds the contributing guide
Fixes #11

[GH-11] Add contributing guide

---

ui/package-lock.json
ui/package.json
ui/public/index.html
ui/src/App.css
ui/src/App.js
ui/src/App.test.js
ui/src/index.css
ui/src/index.js
ui/src/pages/LoginPage.js
ui/src/pages/RegisterPage.js
ui/src/pages/WelcomePage.js

Created a react app and added very basic ui for login, logout and register

React app, login, logout, register

---

server/api/user_test.go
server/functionaltesting/apitestlib.go
server/functionaltesting/user.go
server/server/server.go
server/store/store.go

This PR more or less finalises the functional testing support.
If you want to create functional tests to test api layer(including the real store), you'll have to create the corresponding method in the `Client` object and use it in the regular tests.

[GH-19] Finalise functional testing support

---

.editorconfig
.gitignore
webapp/.eslintignore
webapp/.eslintrc.json
webapp/package-lock.json
webapp/package.json
webapp/src/App.test.js
webapp/src/App.tsx
webapp/src/client/user.ts
webapp/src/index.tsx
webapp/src/pages/LoginPage.tsx
webapp/src/pages/RegisterPage.tsx
webapp/src/pages/WelcomePage.tsx
webapp/webpack.config.js

This PR adds support of eslint
also support of the [editorconfig](http://editorconfig.org/)
Fixes: #35

[GH-35] Add eslint

---

.github/workflows/eslint.yml
.github/workflows/go-test.yml
.github/workflows/golangci-lint.yml

This PR adds GitHub actions for:
1. checking go code style
2. testing go code
3. checking typescript code style
Fixes: #14

[GH-14] Add github actions

---

server/model/user.go
webapp/package-lock.json
webapp/package.json
webapp/src/client/rest.ts
webapp/src/pages/RegisterPage.tsx
webapp/src/types/errors.ts
webapp/src/types/users.ts

This PR adds username to the registration page. It swaps `formik` to `react-hook-form` and adds server error handling In the frontend
Fixes: #24 
You can see the results here
https://user-images.githubusercontent.com/2340127/229493089-fa65fd52-a532-4718-94d2-7c9e33197248.mp4

[GH-24] Add username to the registration

---

server/api/api.go
server/api/node.go
server/api/node_test.go
server/api/user.go
server/app/node.go
server/app/permission.go
server/app/user.go
server/functionaltesting/client.go
server/functionaltesting/node.go
server/model/node.go
server/model/node_options.go
server/model/user_options.go
server/store/migrations.go
server/store/node.go
server/store/store.go

This PR adds node API and store support
fixes: #26

[GH-26] Add node api

---

server/api/jwt.go
server/api/user_test.go
server/functionaltesting/apitestlib.go
server/functionaltesting/client.go
server/functionaltesting/user.go

This PR fixes user login
fixes: #52

[GH-52] Fix user login

---

webapp/package-lock.json
webapp/package.json
webapp/src/client/client.ts
webapp/src/client/graph.ts
webapp/src/components/force_graph.tsx
webapp/src/components/graph.tsx
webapp/src/types/graph.ts

This PR renders knowledge graph.
It's the first and very simple approach. Needs lot's of fine tuning
https://user-images.githubusercontent.com/2340127/233362489-d5bcd288-a27d-48d1-9a63-19f43f19dae4.mp4
Fixes: #63

[GH-63] Render knowledge graph

---

server/api/api.go
server/api/graph.go
server/api/jwt.go
server/api/node.go
server/api/user.go
server/functionaltesting/user.go
webapp/src/client/graph.ts
webapp/src/client/rest.ts
webapp/src/components/graph.tsx

This PR removes the msg field returned from server, since it's redundant.
Fixes: #71

[GH-71] Remove msg field

---

Makefile
prereq-check.sh

This PR adds makefile. Code is self-explanatory
Fixes: #42

[GH-42] Add makefile

---

Dockerfile.server
Dockerfile.webapp
Makefile
docker-compose.yaml
server/Makefile
server/README.md
webapp/Makefile
webapp/webpack.config.js

This PR adds docker support
use ``` make docker-start``` to run server and webapp containers.
Fixes: #7

[GH-7] Add Docker support

---

server/api/api.go
server/api/node.go
server/app/node.go
server/model/node.go
server/model/video.go
server/store/migrations.go
server/store/store.go
server/store/video.go
webapp/src/App.tsx
webapp/src/pages/NodePage.tsx

This PR adds videos to the node.
Fixes: #59

[GH-59] Add videos to node

---

server/model/video.go
server/store/migrations.go
server/store/video.go
webapp/src/App.tsx
webapp/src/client/client.ts
webapp/src/client/node.ts
webapp/src/components/node.tsx
webapp/src/pages/NodePage.tsx
webapp/src/types/graph.ts

This PR adds node to the front end, currently you can see the node name, description and list of videos. Proper design TBD
Fixes: #96

[GH-96] Add node to the front

---

server/api/user_test.go
server/functionaltesting/apitestlib.go
server/functionaltesting/client.go
server/functionaltesting/user.go
server/store/token.go

This PR adds tests for user API. 
For testing purposes, also adds `GetLastToken` to To `TokenStore` so that email verification can be tested
Fixes #45

[GH-45] Add user api tests

---

webapp/package-lock.json
webapp/package.json
webapp/src/components/3d_force_graph.tsx
webapp/src/components/graph.tsx

This PR adds support of the 3d force graph. On main page now we have 3 different graphs, we will fine tune their appearances when size of the graph is substantial.
Fixes: #101

[GH-101] Add 3d force graph

---

server/api/node.go
server/api/user.go
server/app/session.go
server/config/config.go
server/config/config.json
server/functionaltesting/apitestlib.go
server/store/session.go

This PR adds session timeout, session can be extended if user views some node.
Fixes: #111

[GH-111] Add session timeout

---

server/api/auth_middleware.go
server/api/graph.go
server/api/node.go
server/api/user_test.go
server/app/graph.go
server/app/node.go
server/app/user.go
server/model/graph.go
server/model/node.go
server/store/migrations.go
server/store/node.go
server/store/store.go
webapp/src/components/3d_force_graph.tsx
webapp/src/components/react_d3_graph.tsx
webapp/src/types/graph.ts

This PR adds node statuses
Fixes: #104

[GH-104] Add node statuses

---

server/app/email.go
server/config/config.json

This PR sends emails using Gmail SMTP. 
I finished only the BE part. 
FE part to parse the activation link and pass the token to BE needs to be done. 
Fixes #6

[GH-6]: Send email for verification

---

server/api/api.go
server/app/app.go
server/store/store.go
server/store/system.go

This PR adds a health check endpoint. 200 OK if healthy. 500 if not.
Fixes #91

[GH-91]: Add system healthcheck endpoint

---

webapp/src/components/3d_force_graph.tsx
webapp/src/components/graph.tsx
webapp/src/components/graph_rhs.tsx
webapp/src/hooks/use_window_dimensions.tsx

This PR adds graph Right hand side
Fixes: #120

[GH-120] Add graph RHS

---

webapp/src/client/client.ts
webapp/src/client/rest.ts
webapp/src/client/sidebar.ts
webapp/src/components/graph/3d_force_graph.tsx
webapp/src/components/graph/graph_component.tsx
webapp/src/components/graph/graph_rhs.tsx
webapp/src/components/graph/react_d3_graph.tsx
webapp/src/components/lhs/group.tsx
webapp/src/components/lhs/item.tsx
webapp/src/components/lhs/lhs_navigation.tsx
webapp/src/components/lhs/sidebar.tsx
webapp/src/pages/HomePage.tsx
webapp/src/types/graph.ts
webapp/src/types/sidebar.ts

This PR adds left hand side support. Code in LHSNavigation is just for testing and will be removed in later PRs
https://github.com/oseducation/knowledge-graph/assets/2340127/230a1568-82c3-4389-95df-57dde8cf8a50
Fixes: #134

[GH-134] Add lhs

---

server/store/node.go
webapp/src/client/node.ts
webapp/src/components/lhs/group.tsx
webapp/src/components/lhs/item.tsx
webapp/src/components/lhs/lhs_navigation.tsx
webapp/src/components/lhs/sidebar.tsx
webapp/src/components/main.tsx
webapp/src/components/rhs/rhs.tsx
webapp/src/pages/HomePage.tsx

This PR adds support for your nodes(in progress and next).
User can mark a node as known with the LHS menu and the list will update.
Fixes: #122

[GH-122] Add support for your nodes

---

webapp/src/components/graph/3d_force_graph.tsx
webapp/src/components/main.tsx
webapp/src/types/graph.ts

This PR adds colours to different types of graph nodes
Fixes: #123

[GH-123] Add colors to different type of nodes

---

server/app/node.go
server/model/node.go
server/store/user.go
webapp/src/components/graph/3d_force_graph.tsx
webapp/src/components/main.tsx
webapp/src/components/node.tsx
webapp/src/components/rhs/rhs.tsx
webapp/src/types/graph.ts

This PR implement RHS with node details
Fixes: #144 
https://github.com/oseducation/knowledge-graph/assets/2340127/fd0e7218-e397-4d0b-98e7-f0735ff2867b

[GH-144] Implement RHS

---

webapp/src/components/graph/3d_force_graph.tsx
webapp/src/components/graph/graph_component.tsx
webapp/src/components/lhs/item.tsx
webapp/src/components/main.tsx
webapp/src/components/rhs/rhs.tsx
webapp/src/types/sidebar.ts

This PR implements node las onClick function 
https://github.com/oseducation/knowledge-graph/assets/2340127/a31192dc-4618-46f1-aba6-42733b652dae
Fixes: #147

[GH-147] Implement node lhs onClick

---

server/api/api.go
server/api/video.go
server/app/node.go
server/app/video.go
webapp/src/components/lhs/item.tsx
webapp/src/components/lhs/lhs_navigation.tsx
webapp/src/components/lhs/sidebar.tsx
webapp/src/components/node.tsx

This PR adds support of clicking the video on lhs
https://github.com/oseducation/knowledge-graph/assets/2340127/3d99e7b5-cad7-4e8a-8d85-dba6409b6bd5
Fixes: #148

[GH-148] Add video lhs click support

---

Makefile
docker-compose.yaml
server/README.md

Upgrades to docker compose V2
Adds docker targets to Makefile
Updates server Readme

[GH-4]: fixes container names across operation systems

---

Dockerfile.server
docker-compose.yaml

[GH-119] add healcheck to kg-server service

---

.github/workflows/golangci-lint.yml
webapp/src/components/header.tsx
webapp/src/pages/LoginPage.tsx

This PR fixes redirect problem, adds link to `knowledge graph` text as well
Fixes: #161

[GH-161] Fix redirect

---

webapp/package-lock.json
webapp/package.json
webapp/src/components/ProfileDropdown.tsx
webapp/src/components/header.tsx

This PR adds a user profile dropdown
Fixes #130

[GH-130]: Create user profile dropdown

---

server/api/user.go
server/api/user_test.go
server/functionaltesting/user.go
webapp/src/App.tsx
webapp/src/client/user.ts
webapp/src/pages/ProfilePage.tsx

This PR adds a user profile page. it can update the first name last name and username.
Very basic UX. 
Fixes #41

[GH-41]: Create user profile page

---

server/store/user.go
server/store/video.go

This PR fixes Postgres support (`JOIN` is not working without `ON`)

Fix pg support

---

server/README.md
server/app/app.go
server/app/youtube.go
server/functionaltesting/apitestlib.go
webapp/src/components/graph/3d_force_graph.tsx
webapp/src/components/node.tsx
webapp/src/components/rhs/rhs.tsx
webapp/src/types/graph.ts

This PR imports videos from the content repo.

Add import video

---

server/api/node.go
server/app/app.go
server/app/node.go
server/store/migrations.go
server/store/session.go
webapp/src/client/node.ts
webapp/src/components/node.tsx
webapp/src/components/video_input.tsx

This PR adds user videos
Fixes: #181

[GH-181] Add user videos

---

server/api/video.go
server/app/app.go
server/app/graph.go
server/app/video.go
server/store/video.go
webapp/package-lock.json
webapp/package.json
webapp/src/App.tsx
webapp/src/client/video.ts
webapp/src/components/header.tsx
webapp/src/components/node.tsx
webapp/src/components/player.tsx
webapp/src/components/shorts.tsx
webapp/src/pages/ShortsPage.tsx
webapp/src/types/graph.ts
webapp/src/types/history.ts

This PR adds shorts mode
Fixes: #182

[GH-182] Add shorts mode

---

server/api/api.go
server/api/preferences.go
server/app/graph.go
server/app/preferences.go
server/model/preferences.go
server/store/migrations.go
server/store/preferences.go
server/store/store.go
webapp/src/App.tsx
webapp/src/client/rest.ts
webapp/src/client/user.ts
webapp/src/components/ProfileDropdown.tsx
webapp/src/components/graph/3d_force_graph.tsx
webapp/src/components/player.tsx
webapp/src/components/preferences.tsx
webapp/src/components/shorts.tsx
webapp/src/context/auth_provider.tsx
webapp/src/pages/LoginPage.tsx
webapp/src/types/users.ts

This PR adds user settings.
Fixes: #191 
https://github.com/oseducation/knowledge-graph/assets/2340127/c5fea018-e051-4473-8bc6-5000f8619d0e

[GH-191] Add user settings

---

webapp/src/components/rhs/rhs.tsx
webapp/src/types/graph.ts

This PR fixes props "key" warning, we had `undefined` in key props, since active users type was redundant.

Fix key props error

---

CONTRIBUTING.md
README.md
prereq-check.sh
server/README.md
server/app/email.go
webapp/public/index.html
webapp/src/components/footer.tsx
webapp/src/components/header.tsx

[GH-193] Rename to vitsi

---

webapp/src/index.tsx

[GH-211] Limit app to chrome

---

webapp/src/App.tsx
webapp/src/components/footer.tsx
webapp/src/pages/ContactUsPage.tsx

[GH-75] Add contact page

---

webapp/src/App.tsx
webapp/src/pages/PrivacyPage.tsx
webapp/src/pages/TermsPage.tsx

[GH-74] Add terms and privacy info

---

webapp/src/components/player.tsx

[GH-198] Offload Youtube player properly

---

webapp/src/App.tsx
webapp/src/index.tsx

This PR limits app to larger screens only

Limit screen size

---

webapp/src/AppLayout.tsx
webapp/src/components/content.tsx
webapp/src/components/header.tsx

[GH-221] Make homepage responsive

---

webapp/src/AppLayout.tsx
webapp/src/components/ProfileDropdown.tsx
webapp/src/components/header.tsx
webapp/src/components/main.tsx
webapp/src/components/rhs/rhs.tsx
webapp/src/context/auth_provider.tsx
webapp/src/context/drawer_provider.tsx
webapp/src/hooks/useDrawer.tsx

This PR make logged in page responsive
fixes: #223 
https://github.com/oseducation/knowledge-graph/assets/2340127/340ef979-9595-457f-9e01-b45c48ba85f5

[GH-223] Make logged in homepage responsive

---

server/api/user.go
server/config/config.go
server/config/config.json
webapp/src/index.tsx

[GH-200] Add safari support

---

webapp/src/components/graph/3d_force_graph.tsx
webapp/src/components/graph/graph_component.tsx
webapp/src/components/main.tsx

This PR fixes graph visibility, also makes graph fit the window
Fixes: #226 
Fixes: #232

[GH-226] Fix graph visibility

---

server/api/node.go
server/model/node.go
webapp/src/client/node.ts
webapp/src/components/I_konw_this_button.tsx
webapp/src/components/node.tsx
webapp/src/components/node_drop_down.tsx
webapp/src/components/node_title_section.tsx
webapp/src/components/rhs/rhs.tsx
webapp/src/types/graph.ts

https://github.com/oseducation/knowledge-graph/assets/10206427/a632647a-5fcf-4d99-8fa8-dd2e337be5ad
fixes: #208

feat: [GH-208] - Disable "I know this" button

---

webapp/src/components/main.tsx

Fixes https://github.com/oseducation/knowledge-graph/issues/233

fix: [GH-233] - Use toolbar height from theme

---

.github/workflows/golangci-lint.yml
Makefile

[GH-164] Add go mod tidy check

---

webapp/src/components/graph/3d_force_graph.tsx

This PR adds graph highlights on hover
Fixes: #151 
https://github.com/oseducation/knowledge-graph/assets/2340127/7c6f70ae-b50d-4748-a75a-d86f9b439516

[GH-151] Add graph highlights

---

webapp/src/components/carousel.tsx
webapp/src/components/header.tsx

[GH-228] Make carousel responsive

---

webapp/src/Footer.tsx
webapp/src/components/main.tsx
webapp/src/components/node.tsx

[GH-227] node page resp

---

webapp/public/index.html

[GH-129] Add google analytics

---

.github/workflows/docker_ecr_build.yaml
Makefile

[GH-248] Upload webapp to s3

---

webapp/src/App.tsx

[GH-259] Enable mobile

---

webapp/webpack.config.js

[GH-263] Add content hash to bundle name

---

server/api/graph.go
server/api/node_test.go
server/api/user.go
server/api/user_test.go
server/app/graph.go
server/app/preferences.go
server/model/node.go
server/model/user.go
server/store/migrations.go
server/store/node.go
server/store/user.go

[GH-187] Add english language support

---

webapp/src/components/video_input.tsx

[GH-260] Clarify video upload text

---

webapp/src/components/graph/3d_force_graph.tsx

[GH-270] Limit access to nodes with missing prerequisites

---

webapp/src/components/header.tsx

[GH-267] Always show graph button

---

server/store/node.go
webapp/src/components/I_konw_this_button.tsx
webapp/src/components/node.tsx
webapp/src/components/node_title_section.tsx
webapp/src/components/rhs/rhs.tsx

[GH-271] Add support to revisit node

---

server/api/api.go
server/api/text.go
server/app/node.go
server/app/text.go
server/model/node.go
server/model/text.go
server/store/migrations.go
server/store/store.go
server/store/text.go
webapp/package-lock.json
webapp/package.json
webapp/src/components/node.tsx
webapp/src/types/graph.ts

This PR adds markdown text support
Fixes: #58

[GH-58] Add support of markdown texts

---

server/app/app.go
server/store/migrations.go

[GH-279] Import texts

---

webapp/src/components/lhs/lhs_navigation.tsx
webapp/src/components/lhs/sidebar.tsx
webapp/src/components/main.tsx

[GH-301] Remove empty categories

---

webapp/src/components/rhs/rhs.tsx

[GH-316] Limit grey nodes access

---

webapp/src/components/node.tsx
webapp/src/context/auth_provider.tsx

[GH-268] Fix refresh

---

server/api/api.go
server/api/node.go
server/api/question.go
server/app/app.go
server/app/node.go
server/app/question.go
server/model/node.go
server/model/question.go
server/store/migrations.go
server/store/question.go
server/store/store.go
server/store/text.go
webapp/src/components/node.tsx
webapp/src/components/question.tsx
webapp/src/i18n.ts
webapp/src/types/graph.ts

[GH-321] Add questions

---

webapp/package-lock.json
webapp/package.json
webapp/src/client/node.ts
webapp/src/pages/LoginPage.tsx
webapp/src/pages/RegisterPage.tsx

[GH-295] Add KPIs

---

webapp/package-lock.json
webapp/package.json
webapp/src/components/markdown.tsx
webapp/src/components/node.tsx

Adds coding highlights to the markdown, as well as Math rendering
Fixes: #299

[GH-299] markdown styles

---

Makefile
webapp/src/context/auth_provider.tsx

[GH-327] Fix language change

---

webapp/src/components/rhs/rhs.tsx

[GH-326] Fix I know this button

---

server/cmd/commands/db.go
server/config/config.json
server/functionaltesting/apitestlib.go
server/server/server.go

[GH-331] Add nodes from terminal

---

server/app/import.go
server/model/question.go
server/store/migrations.go
server/store/question.go
webapp/src/components/node.tsx
webapp/src/types/graph.ts

[GH-337] Add support of multiple questions

---

webapp/src/components/main.tsx

[GH-298] Sort LHS

---

webapp/src/components/graph/3d_force_graph.tsx
webapp/src/i18n.ts

[GH-304] Add popup on grey node

---

webapp/src/components/header.tsx

[GH-342] Add back button

---

webapp/src/components/question.tsx

[GH-344] Add markdown support to questions

---

webapp/src/components/main.tsx

[GH-347] Reload graph on language change

---

server/api/graph.go
server/api/user.go
server/app/graph.go
webapp/src/App.tsx
webapp/src/client/user.ts
webapp/src/context/auth_provider.tsx
webapp/src/pages/AdminPage.tsx
webapp/src/pages/GraphPage.tsx

[GH-352] Add admin panel

---

server/api/user.go
server/api/user_test.go
server/functionaltesting/apitestlib.go
webapp/src/components/content.tsx
webapp/src/components/header.tsx
webapp/src/components/language_picker.tsx
webapp/src/i18n.ts
webapp/src/pages/LoginPage.tsx
webapp/src/pages/RegisterPage.tsx
webapp/src/types/users.ts

[GH-360] Add language changer

---

server/model/node.go
server/store/migrations.go
server/store/node.go
webapp/src/components/environment.tsx
webapp/src/components/karel/ide.tsx
webapp/src/components/node.tsx
webapp/src/i18n.ts
webapp/src/types/graph.ts

Fixes: #364 
https://github.com/oseducation/knowledge-graph/assets/2340127/6b80f3f9-f8ad-40d3-bd7a-76e3e808c3b1

[GH-364] Add environment link

---

webapp/src/Footer.tsx
webapp/src/components/footer.tsx
webapp/src/components/header.tsx
webapp/src/components/landing/apply.tsx
webapp/src/components/landing/drop_out.tsx
webapp/src/components/landing/explore.tsx
webapp/src/components/landing/hero.tsx
webapp/src/components/landing/learn.tsx
webapp/src/components/landing/problem1.tsx
webapp/src/components/landing/problem2.tsx
webapp/src/components/landing/two_sided_layout.tsx
webapp/src/components/landing/vitsi.tsx
webapp/src/components/language_picker.tsx

Fixes Landing page for small devices

Fix landing

---

webapp/src/App.tsx
webapp/src/components/landing/landing.tsx
webapp/src/pages/HomePage.tsx

[GH-384] Add language paths

---

server/app/node.go
server/model/node.go
server/store/node.go
webapp/src/components/node.tsx
webapp/src/components/node_title_section.tsx
webapp/src/i18n.ts
webapp/src/types/graph.ts

[GH-386] Add prerequisite topics list to node

---

Makefile
server/app/goal.go
server/app/import.go
server/store/goal.go

[GH-391] Import goals

---

server/api/api.go
server/api/post.go
server/app/post.go
server/model/post.go
server/store/migrations.go
server/store/post.go
server/store/store.go

[GH-397] Add posts table

---

server/api/post.go
server/app/app.go
server/app/email.go
server/app/post.go
server/app/user.go
server/model/post.go
server/store/post.go
webapp/src/analytics.ts
webapp/src/client/client.ts
webapp/src/client/post.ts
webapp/src/components/node.tsx
webapp/src/components/rhs/chat_rhs.tsx
webapp/src/components/rhs/post_input.tsx
webapp/src/components/rhs/rhs.tsx
webapp/src/i18n.ts
webapp/src/types/posts.ts

https://github.com/oseducation/knowledge-graph/assets/2340127/75b0ab14-8902-475e-9205-c19c94a2ab17
Fixes: #400

[GH-400] Display posts

---

webapp/src/components/bot/chat.tsx
webapp/src/components/bot/messages.ts
webapp/src/components/bot/use_posts.tsx

[GH-419] Add pending posts

---

server/model/post.go
webapp/src/components/bot/chat.tsx
webapp/src/components/bot/create_post.ts
webapp/src/components/bot/messages.ts
webapp/src/components/bot/post_component.tsx
webapp/src/components/karel/ide.tsx
webapp/src/components/karel/ide_component.tsx
webapp/src/types/posts.ts

[GH-411] Add support of Karel IDE in chat

---

webapp/src/App.tsx
webapp/src/components/dashboard/dashboard_lhs.tsx
webapp/src/components/dashboard/graph.tsx
webapp/src/components/graph/graph_component.tsx
webapp/src/components/header.tsx

[GH-411] Add graph to dashboard

---

.github/workflows/build_and_depoy.yaml

Needs a new github secret "YOUTUBE_API_KEY"

set env variables from github action

---

docker-compose.yaml
server/api/bot.go
server/app/app.go
server/app/bot.go
server/app/import.go
server/app/node.go
server/cmd/commands/db.go
server/config/config.go
server/config/config.json
server/functionaltesting/apitestlib.go
server/model/post.go
server/services/chatgpt.go
server/services/service.go
server/services/youtube.go
server/store/node.go
server/store/post.go
server/store/text.go
webapp/src/client/bot.ts
webapp/src/components/bot/chat.tsx
webapp/src/components/bot/post_component.tsx
webapp/src/types/posts.ts

[GH-412] Add chatGPT integration

---

server/api/bot.go
server/app/bot.go
server/services/chatgpt.go
server/services/chatgpt_steam.go
webapp/src/components/bot/bot_stream_message.tsx
webapp/src/components/bot/chat.tsx
webapp/src/components/bot/messages.ts

[GH-433] Add chat streaming

---

webapp/src/App.tsx
webapp/src/components/overview/activity.tsx
webapp/src/components/overview/goals.tsx
webapp/src/components/overview/overview.tsx
webapp/src/components/overview/progress.tsx
webapp/src/components/overview/snippets.tsx
webapp/src/components/overview/top_performers.tsx

[GH-435] Add snippet front

---

webapp/src/components/overview/activity.tsx
webapp/src/components/overview/progress.tsx
webapp/src/components/overview/snippets.tsx

[GH-439] Add activity front

---

webapp/src/components/overview/top_performers.tsx

[GH-440] Add top performers

---

webapp/src/components/dashboard/dashboard_header.tsx
webapp/src/components/dashboard/dashboard_layout.tsx
webapp/src/components/dashboard/graph.tsx
webapp/src/components/dashboard/search_bar.tsx
webapp/src/components/graph/3d_force_graph.tsx
webapp/src/components/graph/graph_component.tsx
webapp/src/components/main.tsx
webapp/src/components/rhs/rhs.tsx
webapp/src/context/graph_provider.tsx

[GH-197] Add search functionality

---

server/api/goal.go
server/model/goal.go
server/store/goal.go
webapp/src/client/graph.ts
webapp/src/components/graph/3d_force_graph.tsx
webapp/src/components/rhs/rhs.tsx
webapp/src/context/graph_provider.tsx
webapp/src/pages/GraphPage.tsx

[GH-408] Goal picking

---

server/api/goal.go
server/app/goal.go
server/store/goal.go
webapp/src/client/graph.ts
webapp/src/components/bot/chat.tsx
webapp/src/components/graph/3d_force_graph.tsx
webapp/src/components/rhs/rhs.tsx
webapp/src/context/graph_provider.tsx
webapp/src/types/graph.ts

[GH-452] Add support of multiple goals

---

README.md
server/README.md
server/services/chatgpt.go
webapp/src/components/footer.tsx
webapp/src/pages/ContactUsPage.tsx

[GH-461] Update readme, remove chat api key requirement

---

server/app/goal.go
server/model/goal.go
server/store/goal.go
webapp/src/types/graph.ts

[GH-453] Add thumbnails to goals

---

server/app/graph.go
server/model/graph.go
server/model/node.go
server/store/migrations.go
server/store/node.go
webapp/src/components/dashboard/dashboard_header.tsx
webapp/src/components/dashboard/dashboard_layout.tsx
webapp/src/components/dashboard/search_bar.tsx
webapp/src/components/graph/3d_force_graph.tsx
webapp/src/components/rhs/rhs.tsx
webapp/src/context/graph_provider.tsx
webapp/src/types/graph.ts

Fixes: #393
See details: 
https://github.com/oseducation/knowledge-graph/assets/2340127/04962821-fa03-4595-8a8e-2e84a7ae8a59

[GH-393] Add support of parent nodes

---

server/api/api.go
server/api/interaction.go
server/app/user_interaction.go
server/model/user_interaction.go
server/store/migrations.go
server/store/store.go
server/store/user_interaction.go
webapp/src/client/user.ts
webapp/src/components/player.tsx
webapp/src/components/time_tracker.tsx
webapp/src/types/users.ts

[GH-467] Add video tracking

---

webapp/src/components/graph/3d_force_graph.tsx

Hello! 
This PR closes #311. 
We disabled node drag as mentioned in the description. View the video below to see how it works on our system 😊
https://github.com/oseducation/knowledge-graph/assets/42633377/a5022df8-2ccc-43ee-8f52-29ddbc6137a1

Disable node drag

---

server/api/api.go
server/api/dashboard.go
server/api/interaction.go
server/model/node.go
server/store/migrations.go
server/store/node.go
webapp/src/client/client.ts
webapp/src/client/dashboard.ts
webapp/src/components/overview/snippets.tsx
webapp/src/types/dashboard.ts

[GH-471] Add finished topics

---

webapp/src/components/bot/chat.tsx
webapp/src/components/overview/goals.tsx
webapp/src/context/graph_provider.tsx

[GH-479] Fix next node

---

server/api/dashboard.go
server/model/user.go
server/store/node.go
webapp/src/client/dashboard.ts
webapp/src/components/overview/top_performers.tsx
webapp/src/types/users.ts

[GH-448] Add top performers

---

Makefile
server/app/import.go
webapp/src/components/main.tsx

[GH-482] Import parent nodes

---

server/store/node.go
webapp/src/components/bot/chat.tsx
webapp/src/context/graph_provider.tsx

[GH-483] fix pg errors

---

webapp/src/components/overview/goals.tsx

[GH-489] Fix goal percentage

---

server/api/dashboard.go
server/store/node.go
webapp/src/client/dashboard.ts
webapp/src/components/overview/snippets.tsx
webapp/src/types/dashboard.ts

[GH-457] Add learning steak

---

server/api/bot.go
server/api/dashboard.go
server/app/bot.go
server/model/post.go
webapp/src/client/dashboard.ts
webapp/src/components/overview/snippets.tsx
webapp/src/types/dashboard.ts

[GH-458] Add AI number of questions

---

webapp/src/components/dashboard/dashboard_header.tsx
webapp/src/components/dashboard/dashboard_layout.tsx
webapp/src/components/overview/goals.tsx
webapp/src/components/overview/overview.tsx
webapp/src/components/overview/snippets.tsx

[GH-406] Make overview responsive

---

webapp/src/components/dashboard/dashboard_header.tsx
webapp/src/components/header.tsx
webapp/src/components/profile_dropdown.tsx

[GH-497] Fix dropdown

---

webapp/src/App.tsx
webapp/src/UserLayout.tsx
webapp/src/components/dashboard/dashboard_layout.tsx
webapp/src/components/dashboard/dashboard_lhs.tsx
webapp/src/components/header.tsx
webapp/src/components/rhs/rhs.tsx
webapp/src/components/time_tracker.tsx
webapp/src/context/graph_provider.tsx
webapp/src/index.tsx

[GH-429] Switch to dashboard

---

webapp/src/App.tsx
webapp/src/components/bot/ai_tutor_chat.tsx
webapp/src/components/bot/create_post.ts
webapp/src/components/bot/messages.ts
webapp/src/components/bot/post_component.tsx
webapp/src/components/bot/use_posts.tsx
webapp/src/components/dashboard/dashboard_lhs.tsx

Fixes: #470 
Created from here https://github.com/oseducation/knowledge-graph/pull/485

[GH-470] Vinayakhegde1 renamed chat aitutor

---

server/app/goal.go
server/model/node.go
server/store/goal.go
server/store/migrations.go
server/store/node.go

[GH-512Add thumbnails to nodes

---

server/app/import.go
server/model/node.go
webapp/src/components/graph/3d_force_graph.tsx
webapp/src/context/graph_provider.tsx
webapp/src/types/graph.ts

[GH-516] Add general topic type

---

server/model/experiment.go
webapp/src/App.tsx
webapp/src/client/experiments.ts
webapp/src/components/experiments/engineer.tsx
webapp/src/components/experiments/one_pager_with_pic.tsx

[GH-524] Add engineer experiment

---

server/model/node.go
server/store/goal.go

[GH-540] fix update

---

webapp/package-lock.json
webapp/package.json
webapp/src/App.tsx
webapp/webpack.config.js

[GH-312] Implement lazy load

---

webapp/src/components/bot/post_component.tsx
webapp/src/components/link_fallback.tsx
webapp/src/components/message_link_fallback.tsx
webapp/src/components/video_fallback.tsx
webapp/src/utils/index.tsx

**_Notice: Failed to attach video of the screen recording couple of times due to size reasons & got frustrated and attached images;)_**
Non last videos are shown as links that when clicked opens a new tab & youtube video in it:
Last videos are shown inside of player:
- Will need instructions on how to import data that'll use karel IDE. Haven't tested it yet. Which data(from contents)/or which make command should i use to have AI assistant talk to me about karel ?

Kg 478 old messages rendering update

---

server/services/chatgpt.go
server/services/chatgpt_steam.go

[GH-565] Add fixes empty GPT API key

---

server/api/user_test.go
server/model/user.go
webapp/src/pages/RegisterPage.tsx

[GH-561] Require name

---

webapp/src/components/bot/messages.ts

[GH-563] Add update first message

---

webapp/src/components/bot/ai_tutor_chat.tsx
webapp/src/components/bot/graph_message.tsx
webapp/src/components/bot/post_component.tsx
webapp/src/components/bot/post_container.tsx
webapp/src/components/dashboard/graph.tsx
webapp/src/components/graph/3d_force_graph.tsx
webapp/src/components/graph/graph_component.tsx
webapp/src/components/landing/two_sided_layout.tsx
webapp/src/context/graph_provider.tsx
webapp/src/pages/GraphPage.tsx

[GH-571] Add support for the graph message

---

webapp/src/components/dashboard/graph.tsx
webapp/src/context/graph_provider.tsx

[GH-573] Show startup nodes only

---

server/app/goal.go
server/store/goal.go

[GH-575] Return 3 goals from server

---

webapp/src/components/dashboard/dashboard_lhs.tsx

[GH-577] Remove goals and badges

---

webapp/src/components/bot/messages.ts
webapp/src/components/dashboard/search_bar.tsx

[GH-535] Add various fixes

---

webapp/src/App.tsx
webapp/src/client/graph.ts
webapp/src/components/landing/course/content.tsx
webapp/src/components/landing/course/course_startup_school_main.tsx
webapp/src/components/landing/course/hero.tsx
webapp/src/components/landing/course/what_you_learn.tsx
webapp/src/context/graph_provider.tsx

[GH-554] Add startup-school landing page

---

server/store/node.go

Fix progress on the dashboard

---

server/api/post.go
webapp/src/App.tsx
webapp/src/components/bot/ai_tutor_chat_general.tsx
webapp/src/pages/AdminPage.tsx

[GH-586] Add chat view

---

webapp/src/components/bot/messages.ts
webapp/src/components/bot/video_message.tsx

[GH-588] update first message

---

webapp/src/components/bot/ai_tutor_chat.tsx
webapp/src/components/bot/ai_tutor_chat_general.tsx

[GH-551] Remove smooth behavior

---

webapp/package-lock.json
webapp/package.json
webapp/src/components/overview/overview.tsx

[GH-591] Add feedback service

---

webapp/src/components/graph/graph_component.tsx

[GH-597] Fix graph flickering

---

server/api/bot.go
server/app/bot.go
server/services/pinecone.go
webapp/src/components/bot/ai_tutor_chat.tsx

[GH-599] Add support for user intent

---

server/app/bot.go
server/services/chatgpt.go
webapp/src/components/bot/ai_tutor_chat.tsx

[GH-601] Add GPT 4 support

---

server/app/bot.go

[GH-604] Fix first topic prerequisites

---

webapp/src/components/landing/founders/apply.tsx
webapp/src/components/landing/founders/courses.tsx
webapp/src/components/landing/founders/hero.tsx
webapp/src/components/landing/founders/landing.tsx
webapp/src/components/landing/vitsi.tsx

[GH-606] Update landing page

---

webapp/src/components/bot/ai_tutor_chat.tsx

[GH-608] Fix tawk for chat

---

webapp/src/components/bot/ai_tutor_chat.tsx
webapp/src/components/bot/graph_message.tsx
webapp/src/components/bot/messages.ts
webapp/src/components/rhs/rhs.tsx
webapp/src/context/graph_provider.tsx

[GH-612] Fix goal change

---

webapp/src/components/overview/goals.tsx

[GH-617] Forward continue button to chat

---

webapp/src/components/bot/graph_message.tsx
webapp/src/components/dashboard/graph.tsx
webapp/src/components/graph/3d_force_graph.tsx
webapp/src/components/graph/legend.tsx
webapp/src/types/users.ts

[GH-615] Add graph legend

---

webapp/src/components/bot/ai_tutor_chat.tsx

[GH-610] Sent message with just enter

---

webapp/src/components/bot/ai_tutor_chat.tsx
webapp/src/components/bot/graph_message.tsx
webapp/src/components/bot/input_component.tsx
webapp/src/components/bot/post_component.tsx
webapp/src/components/bot/video_message.tsx

[GH-614] Add persistant video

---

server/api/bot.go
server/api/post.go
server/model/post.go
server/store/post.go

[GH-623] Limit number of posts

---

webapp/src/App.tsx
webapp/src/components/header.tsx
webapp/src/components/landing/founders/landing.tsx
webapp/src/components/pricing/pricing_card.tsx
webapp/src/components/pricing/pricing_table.tsx

[GH-627] Add pricing on landing

---

webapp/src/components/dashboard/dashboard_lhs.tsx
webapp/src/components/pricing/pricing_table.tsx
webapp/src/components/pricing/upgrade_modal.tsx
webapp/src/pages/ProfilePage.tsx
webapp/src/types/users.ts

[GH-593] Add subscription upgrade front

---

server/api/subscription.go
server/api/user.go
server/app/subscription.go
server/app/user.go
server/model/customer.go
server/model/user.go
server/services/stripe.go
server/store/customer.go
server/store/migrations.go
webapp/src/components/pricing/upgrade_modal.tsx

[GH-531] Add stripe subscription support

---

server/api/bot.go
server/api/user.go
server/app/bot.go
server/app/session.go
server/model/role.go
server/model/user.go
server/services/chatgpt.go
webapp/src/App.tsx
webapp/src/components/dashboard/dashboard_lhs.tsx
webapp/src/pages/ProfilePage.tsx
webapp/src/types/users.ts

[GH-633] Honor subscription

---

webapp/src/components/pricing/upgrade_modal.tsx
webapp/src/pages/ProfilePage.tsx

[GH-637] Make stripe subscriptions live

---

docker-compose.yaml

[GH-639] Change healthcheck interval

---

server/api/api.go
server/api/tutor_personality.go
server/app/bot.go
server/model/tutor_personality.go
server/store/preferences.go
webapp/src/client/user.ts
webapp/src/components/preferences.tsx
webapp/src/context/auth_provider.tsx
webapp/src/types/users.ts

[GH-641] Add tutor personalities

---

webapp/src/client/user.ts
webapp/src/components/bot/ai_tutor_chat.tsx
webapp/src/components/bot/bot_component.tsx
webapp/src/components/bot/bot_stream_message.tsx
webapp/src/components/bot/input_component.tsx
webapp/src/components/bot/post_component.tsx
webapp/src/components/bot/post_container.tsx
webapp/src/components/preferences.tsx
webapp/src/types/tutor_personalities.ts
webapp/src/types/users.ts

[GH-644] Add support to change tutor personality from chat

---

webapp/src/components/node.tsx
webapp/src/components/player.tsx
webapp/src/components/player_overlay.tsx

[GH-646] Add video overlay

---

server/app/import.go

[GH-648] Fix question import

---

server/model/question.go
server/store/migrations.go
server/store/question.go
webapp/src/types/graph.ts

[GH-650] Add explanation

---

webapp/src/components/bot/ai_tutor_chat.tsx
webapp/src/components/bot/conversation_status.tsx
webapp/src/components/bot/create_post.ts
webapp/src/components/bot/messages.ts
webapp/src/components/bot/use_converstion.tsx

[GH-653] Refactor AI tutor chat

---

webapp/src/components/bot/messages.ts
webapp/src/components/player.tsx

[GH-661] Change Vitsi Overview video

---

webapp/src/components/bot/conversation_status.tsx

[GH-655] Update goal change

---

webapp/src/components/bot/post_container.tsx
webapp/src/components/bot/video_message.tsx

[GH-665] Fix chat Responsiveness

---

server/api/api.go
server/api/node_note.go
server/app/node_note.go
server/model/node_note.go
server/store/migrations.go
server/store/node_note.go
server/store/store.go

[Gh-667] notes backend

---

webapp/src/components/bot/bot_stream_message.tsx
webapp/src/components/bot/text_message.tsx

[GH-669] remove extra new lines

---

webapp/src/components/dashboard/dashboard_lhs_group.tsx
webapp/src/components/dashboard/dashboard_lhs_item.tsx
webapp/src/components/dashboard/notes_lhs.tsx
webapp/src/context/auth_provider.tsx

[GH-672] Add note items on dashboard LHS

---

server/api/node_note.go
server/model/node_note.go
server/store/node_note.go
webapp/src/client/user.ts
webapp/src/components/dashboard/dashboard_lhs.tsx
webapp/src/components/dashboard/notes_lhs.tsx
webapp/src/components/rhs/note_editor_rhs.tsx
webapp/src/components/rhs/tiptap_editor.tsx
webapp/src/context/auth_provider.tsx
webapp/src/types/users.ts

[GH-674] create new note

---

server/api/node_note.go
server/store/migrations.go
server/store/node_note.go
webapp/src/client/user.ts
webapp/src/components/dashboard/dashboard_lhs_item.tsx
webapp/src/components/dashboard/notes_lhs.tsx
webapp/src/components/rhs/tiptap_editor.tsx

[GH-676] Add support for deleting a note

---

webapp/src/components/dashboard/dashboard_lhs.tsx
webapp/src/components/dashboard/dashboard_lhs_item.tsx
webapp/src/components/dashboard/notes_lhs.tsx
webapp/src/components/rhs/note_editor_rhs.tsx
webapp/src/components/rhs/tiptap_editor.tsx

[GH-675] Add rename note

---

server/api/user.go
server/app/email.go
server/app/user.go
server/model/session.go
server/model/token.go
server/model/user.go
webapp/src/App.tsx
webapp/src/client/user.ts
webapp/src/components/rhs/tiptap_editor.tsx
webapp/src/pages/LoginPage.tsx
webapp/src/pages/ResetPasswordCompletePage.tsx
webapp/src/pages/ResetPasswordPage.tsx

[GH-542] Add reset password flow

---

server/config/config.json

[GH-685] Update email

---

server/api/bot.go
server/services/chatgpt.go

[GH-687] Update to gpt4o

---

server/app/app.go
server/app/email.go
server/cmd/commands/test.go
server/services/email.go
server/services/service.go

[GH-689] Add email service support

---

webapp/src/components/autofill_aware_textfield.tsx
webapp/src/pages/LoginPage.tsx
webapp/src/pages/RegisterPage.tsx
webapp/src/pages/ResetPasswordCompletePage.tsx
webapp/src/pages/ResetPasswordPage.tsx

[GH-691] Fix autofilled fields

---

webapp/src/App.tsx
webapp/src/components/header.tsx
webapp/src/components/onboarding/body.tsx
webapp/src/components/onboarding/goal_chooser.tsx
webapp/src/components/onboarding/graph.tsx
webapp/src/components/onboarding/learning_style_chooser.tsx
webapp/src/components/onboarding/onboarding.tsx
webapp/src/components/onboarding/stepper.tsx
webapp/src/components/onboarding/time_chooser.tsx
webapp/src/pages/OnboardingPage.tsx
webapp/src/types/onboarding.ts

[GH-695] Add v1 onboarding

---

.gitignore
server/api/question.go
server/app/question.go
server/store/migrations.go
server/store/question.go

[GH-697] Add onboarding quiz backend

---

webapp/src/App.tsx
webapp/src/components/graph/3d_force_graph.tsx
webapp/src/components/graph/graph_component.tsx
webapp/src/pages/GraphManipulationPage.tsx

[GH-703] Add support for graph helper

---

webapp/src/components/graph/graph_helpers.tsx
webapp/src/pages/GraphManipulationPage.tsx

[GH-706] Add graph helpers

---

webapp/src/pages/GraphManipulationPage.tsx

[GH-708] Reorder search for graph helpers

---

server/app/import.go
server/cmd/commands/db.go
server/model/question.go
server/store/migrations.go
server/store/question.go

[GH-710] Fix onboarding question's import

---

webapp/src/components/landing/simple/header.tsx
webapp/src/components/onboarding/goal_chooser.tsx
webapp/src/components/onboarding/learning_style_chooser.tsx
webapp/src/components/onboarding/onboarding.tsx
webapp/src/components/onboarding/time_chooser.tsx

[GH-712] Update texts for onboarding flow

---

server/model/graph.go
server/store/question.go
webapp/src/client/onboarding.ts
webapp/src/components/bot/question_choices.tsx
webapp/src/components/dashboard/graph.tsx
webapp/src/components/dashboard/search_bar.tsx
webapp/src/components/graph/3d_force_graph.tsx
webapp/src/components/graph/graph_helpers.tsx
webapp/src/components/node_title_section.tsx
webapp/src/components/onboarding/onboarding.tsx
webapp/src/components/onboarding/quiz_question.tsx
webapp/src/components/onboarding/stepper.tsx
webapp/src/components/overview/goals.tsx
webapp/src/components/rhs/rhs.tsx
webapp/src/context/graph_provider.tsx
webapp/src/pages/GraphManipulationPage.tsx
webapp/src/types/graph.ts

[GH-714] Update graph during onboarding flow

---

webapp/src/pages/GraphManipulationPage.tsx

[GH-716] Node type filter for graph manipulation

---

webapp/src/components/graph/graph_helpers.tsx
webapp/src/components/landing/course/content.tsx
webapp/src/components/onboarding/onboarding.tsx
webapp/src/context/graph_provider.tsx
webapp/src/pages/GraphManipulationPage.tsx
webapp/src/types/graph.ts

[GH-718] Add support for multiple courses in the frontend

---

server/api/user.go
server/app/graph.go
server/app/user.go
server/functionaltesting/user.go
server/model/model.go
server/model/user.go
server/store/migrations.go
server/store/user.go
webapp/src/client/user.ts
webapp/src/components/onboarding/onboarding.tsx
webapp/src/components/registration.tsx
webapp/src/types/onboarding.ts

[GH-720] Set goals from onboarding

---

server/app/import.go
webapp/package-lock.json
webapp/package.json
webapp/src/components/markdown.tsx

[GH-723] Add remarkGFM

---

webapp/src/App.tsx
webapp/src/analytics.ts
webapp/src/components/landing/simple/header.tsx
webapp/src/components/landing/tutoring/tutoring_benefits.tsx
webapp/src/components/landing/tutoring/tutoring_hero.tsx
webapp/src/components/landing/tutoring/tutoring_main.tsx

[GH-734] Add tutoring landing page

---

webapp/src/App.tsx
webapp/webpack.config.js

[GH-737] Minimize bundle size with lazy
